#!/bin/bash

set -ex

cd $(dirname $0)

cp ~/.zshrc .zshrc
cp ~/.yabairc .yabairc
cp ~/.skhdrc .skhdrc || true
cp ~/.tmux.conf .tmux.conf
rsync -av ~/.config/nvim .config/nvim

git submodule foreach git pull

set +x
git add .
git status
echo -n "Push ? [Y/n]: "
read push
if [[ ${push} == "Y" ]]; then
	git commit -m "Mac collections collector collected"
	git push
fi
