#!/bin/bash

set -ex

cp ~/.zshrc .zshrc
cp ~/.yabairc .yabairc
cp ~/.skhdrc .skhdrc || true
cp ~/.tmux.conf .tmux.conf
cp -r ~/.config .config

git submodule foreach git pull

set +x
echo -n "Push ? [Y/n]: "
read push
if [[ ${push} == "Y" ]]; then
	git add .
	git commit -m "Mac collections collector collected"
	git push
fi
